import type { User, Category, Item, Conversation, Message, Notification, Review } from "@/types";

export const CATEGORIES: Category[] = [
  { id: "1", name: "Abbigliamento", slug: "abbigliamento", icon: "Shirt", itemCount: 234 },
  { id: "2", name: "Elettronica", slug: "elettronica", icon: "Smartphone", itemCount: 89 },
  { id: "3", name: "Casa e Giardino", slug: "casa-giardino", icon: "Home", itemCount: 156 },
  { id: "4", name: "Libri", slug: "libri", icon: "BookOpen", itemCount: 312 },
  { id: "5", name: "Sport", slug: "sport", icon: "Dumbbell", itemCount: 67 },
  { id: "6", name: "Giocattoli", slug: "giocattoli", icon: "Gamepad2", itemCount: 98 },
  { id: "7", name: "Musica e Film", slug: "musica-film", icon: "Music", itemCount: 45 },
  { id: "8", name: "Veicoli", slug: "veicoli", icon: "Bike", itemCount: 23 },
  { id: "9", name: "Animali", slug: "animali", icon: "PawPrint", itemCount: 34 },
  { id: "10", name: "Altro", slug: "altro", icon: "Package", itemCount: 78 },
];

export const MOCK_USERS: User[] = [
  {
    id: "user-1",
    username: "marco_verde",
    displayName: "Marco Rossi",
    bio: "Amo dare nuova vita alle cose! Minimalista convinto.",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Marco",
    locationName: "Milano, Navigli",
    karmaPoints: 2450,
    karmaLevel: 5,
    isVerified: true,
    itemsGiven: 47,
    itemsReceived: 12,
    rating: 4.8,
    reviewCount: 35,
    followersCount: 128,
    followingCount: 45,
    badges: ["first_gift", "generous_50", "eco_warrior", "top_rated"],
    createdAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "user-2",
    username: "giulia_eco",
    displayName: "Giulia Bianchi",
    bio: "Sgombero casa! Tante cose belle cercano una nuova famiglia.",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Giulia",
    locationName: "Roma, Trastevere",
    karmaPoints: 1820,
    karmaLevel: 4,
    isVerified: true,
    itemsGiven: 31,
    itemsReceived: 8,
    rating: 4.9,
    reviewCount: 28,
    followersCount: 95,
    followingCount: 62,
    badges: ["first_gift", "generous_10", "top_rated"],
    createdAt: "2024-05-20T14:30:00Z",
  },
  {
    id: "user-3",
    username: "luca_share",
    displayName: "Luca Ferrari",
    bio: "Condividere e meglio che possedere.",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Luca",
    locationName: "Torino, San Salvario",
    karmaPoints: 980,
    karmaLevel: 3,
    isVerified: false,
    itemsGiven: 15,
    itemsReceived: 22,
    rating: 4.5,
    reviewCount: 12,
    followersCount: 34,
    followingCount: 78,
    badges: ["first_gift", "generous_10"],
    createdAt: "2024-08-10T09:15:00Z",
  },
  {
    id: "user-4",
    username: "sara_gift",
    displayName: "Sara Conti",
    bio: "Mamma di due bimbi, regalo tutto cio che non usano piu!",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Sara",
    locationName: "Bologna, Centro",
    karmaPoints: 3200,
    karmaLevel: 6,
    isVerified: true,
    itemsGiven: 68,
    itemsReceived: 5,
    rating: 5.0,
    reviewCount: 52,
    followersCount: 210,
    followingCount: 30,
    badges: ["first_gift", "generous_50", "eco_warrior", "top_rated", "community_builder"],
    createdAt: "2024-01-05T16:45:00Z",
  },
  {
    id: "user-5",
    username: "ale_minimal",
    displayName: "Alessandro Moretti",
    bio: "Decluttering in corso! Tutto deve andare.",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Alessandro",
    locationName: "Firenze, Oltrarno",
    karmaPoints: 560,
    karmaLevel: 2,
    isVerified: false,
    itemsGiven: 8,
    itemsReceived: 15,
    rating: 4.3,
    reviewCount: 6,
    followersCount: 18,
    followingCount: 42,
    badges: ["first_gift"],
    createdAt: "2025-01-12T11:20:00Z",
  },
];

export const CURRENT_USER = MOCK_USERS[0];

const IMG = "https://picsum.photos/seed";

export const MOCK_ITEMS: Item[] = [
  {
    id: "item-1",
    userId: "user-2",
    user: MOCK_USERS[1],
    title: "Giacca invernale Zara taglia M",
    description: "Giacca invernale in ottimo stato, indossata solo una stagione. Colore blu navy, taglia M. Perfetta per l'inverno!",
    condition: "like_new",
    status: "active",
    listingType: "free",
    categoryId: "1",
    category: CATEGORIES[0],
    images: [`${IMG}/jacket1/400/400`, `${IMG}/jacket2/400/400`, `${IMG}/jacket3/400/400`],
    locationName: "Roma, Trastevere",
    viewCount: 45,
    favoriteCount: 12,
    requestCount: 3,
    createdAt: "2026-03-28T10:00:00Z",
    isFavorited: false,
  },
  {
    id: "item-2",
    userId: "user-4",
    user: MOCK_USERS[3],
    title: "Passeggino Chicco Liteway",
    description: "Passeggino leggero e pratico, usato per 1 anno. Funziona perfettamente, qualche segno d'uso ma strutturalmente perfetto.",
    condition: "good",
    status: "active",
    listingType: "offerta_libera",
    categoryId: "6",
    category: CATEGORIES[5],
    images: [`${IMG}/stroller1/400/400`, `${IMG}/stroller2/400/400`],
    locationName: "Bologna, Centro",
    viewCount: 89,
    favoriteCount: 24,
    requestCount: 7,
    createdAt: "2026-03-27T14:30:00Z",
    isFavorited: true,
  },
  {
    id: "item-3",
    userId: "user-3",
    user: MOCK_USERS[2],
    title: "Collezione libri Harry Potter completa",
    description: "Tutti e 7 i libri della saga in italiano, edizione Salani. Qualche pagina ingiallita ma tutti in buone condizioni.",
    condition: "good",
    status: "active",
    listingType: "free",
    categoryId: "4",
    category: CATEGORIES[3],
    images: [`${IMG}/books1/400/400`, `${IMG}/books2/400/400`],
    locationName: "Torino, San Salvario",
    viewCount: 156,
    favoriteCount: 42,
    requestCount: 15,
    createdAt: "2026-03-26T09:15:00Z",
    isFavorited: false,
  },
  {
    id: "item-4",
    userId: "user-1",
    user: MOCK_USERS[0],
    title: "Monitor Samsung 24 pollici Full HD",
    description: "Monitor Samsung da 24 pollici, risoluzione Full HD 1920x1080. Perfetto per studio o lavoro. Regalo perche ho preso un ultrawide.",
    condition: "like_new",
    status: "active",
    listingType: "offerta_libera",
    categoryId: "2",
    category: CATEGORIES[1],
    images: [`${IMG}/monitor1/400/400`, `${IMG}/monitor2/400/400`],
    locationName: "Milano, Navigli",
    viewCount: 203,
    favoriteCount: 56,
    requestCount: 22,
    createdAt: "2026-03-25T16:45:00Z",
    isFavorited: false,
  },
  {
    id: "item-5",
    userId: "user-5",
    user: MOCK_USERS[4],
    title: "Set di pentole antiaderenti",
    description: "Set completo di 5 pentole con coperchi. Usate ma in buone condizioni, nessun graffio sul rivestimento antiaderente.",
    condition: "good",
    status: "active",
    listingType: "free",
    categoryId: "3",
    category: CATEGORIES[2],
    images: [`${IMG}/pots1/400/400`, `${IMG}/pots2/400/400`],
    locationName: "Firenze, Oltrarno",
    viewCount: 67,
    favoriteCount: 18,
    requestCount: 5,
    createdAt: "2026-03-30T08:00:00Z",
    isFavorited: true,
  },
  {
    id: "item-6",
    userId: "user-2",
    user: MOCK_USERS[1],
    title: "Chitarra acustica Yamaha F310",
    description: "Chitarra acustica per principianti, ottime condizioni. Include custodia morbida e plettri. Perfetta per chi vuole iniziare!",
    condition: "like_new",
    status: "active",
    listingType: "offerta_libera",
    categoryId: "7",
    category: CATEGORIES[6],
    images: [`${IMG}/guitar1/400/400`, `${IMG}/guitar2/400/400`, `${IMG}/guitar3/400/400`],
    locationName: "Roma, Trastevere",
    viewCount: 134,
    favoriteCount: 38,
    requestCount: 11,
    createdAt: "2026-03-29T12:00:00Z",
    isFavorited: false,
  },
  {
    id: "item-7",
    userId: "user-3",
    user: MOCK_USERS[2],
    title: "Bicicletta da citta vintage",
    description: "Bici vintage anni 80, restaurata. Funzionante, freni nuovi. Ideale per girare in citta con stile!",
    condition: "fair",
    status: "active",
    listingType: "offerta_libera",
    categoryId: "8",
    category: CATEGORIES[7],
    images: [`${IMG}/bike1/400/400`, `${IMG}/bike2/400/400`],
    locationName: "Torino, San Salvario",
    viewCount: 178,
    favoriteCount: 45,
    requestCount: 9,
    createdAt: "2026-03-24T15:30:00Z",
    isFavorited: false,
  },
  {
    id: "item-8",
    userId: "user-4",
    user: MOCK_USERS[3],
    title: "Scarpe Nike Air Max 270 taglia 42",
    description: "Scarpe da ginnastica Nike, usate poche volte. Taglia 42, colore bianco/nero. Ottime condizioni!",
    condition: "like_new",
    status: "active",
    listingType: "free",
    categoryId: "1",
    category: CATEGORIES[0],
    images: [`${IMG}/shoes1/400/400`, `${IMG}/shoes2/400/400`],
    locationName: "Bologna, Centro",
    viewCount: 92,
    favoriteCount: 28,
    requestCount: 8,
    createdAt: "2026-03-31T11:00:00Z",
    isFavorited: false,
  },
  {
    id: "item-9",
    userId: "user-5",
    user: MOCK_USERS[4],
    title: "Tappetino yoga con borsa",
    description: "Tappetino yoga antiscivolo 6mm, colore verde. Include borsa per trasporto. Usato pochissimo.",
    condition: "like_new",
    status: "active",
    listingType: "free",
    categoryId: "5",
    category: CATEGORIES[4],
    images: [`${IMG}/yoga1/400/400`],
    locationName: "Firenze, Oltrarno",
    viewCount: 34,
    favoriteCount: 9,
    requestCount: 2,
    createdAt: "2026-04-01T07:30:00Z",
    isFavorited: false,
  },
  {
    id: "item-10",
    userId: "user-1",
    user: MOCK_USERS[0],
    title: "Cuscini decorativi set da 4",
    description: "Set di 4 cuscini decorativi per divano, colori neutri (beige e grigio). Lavati e pronti all'uso. Cambio arredamento!",
    condition: "good",
    status: "active",
    listingType: "free",
    categoryId: "3",
    category: CATEGORIES[2],
    images: [`${IMG}/cushions1/400/400`, `${IMG}/cushions2/400/400`],
    locationName: "Milano, Navigli",
    viewCount: 56,
    favoriteCount: 15,
    requestCount: 4,
    createdAt: "2026-04-01T14:00:00Z",
    isFavorited: false,
  },
  {
    id: "item-11",
    userId: "user-2",
    user: MOCK_USERS[1],
    title: "Cuffie Bluetooth Sony WH-1000XM3",
    description: "Cuffie wireless con cancellazione del rumore. Funzionano perfettamente, batteria ancora buona. Upgrade alle XM5.",
    condition: "good",
    status: "active",
    listingType: "offerta_libera",
    categoryId: "2",
    category: CATEGORIES[1],
    images: [`${IMG}/headphones1/400/400`, `${IMG}/headphones2/400/400`],
    locationName: "Roma, Trastevere",
    viewCount: 245,
    favoriteCount: 67,
    requestCount: 19,
    createdAt: "2026-03-30T16:00:00Z",
    isFavorited: true,
  },
  {
    id: "item-12",
    userId: "user-4",
    user: MOCK_USERS[3],
    title: "Giochi da tavolo - lotto di 5",
    description: "Risiko, Monopoly, Cluedo, Dixit e Catan. Tutti completi con tutte le pedine. I bimbi sono cresciuti!",
    condition: "good",
    status: "active",
    listingType: "free",
    categoryId: "6",
    category: CATEGORIES[5],
    images: [`${IMG}/boardgames1/400/400`, `${IMG}/boardgames2/400/400`],
    locationName: "Bologna, Centro",
    viewCount: 167,
    favoriteCount: 48,
    requestCount: 14,
    createdAt: "2026-03-29T09:00:00Z",
    isFavorited: false,
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "conv-1",
    item: MOCK_ITEMS[0],
    participants: [MOCK_USERS[0], MOCK_USERS[1]],
    lastMessage: {
      id: "msg-1",
      conversationId: "conv-1",
      senderId: "user-2",
      content: "Ciao! La giacca e ancora disponibile?",
      isSystem: false,
      createdAt: "2026-04-01T15:30:00Z",
      isRead: false,
    },
    unreadCount: 1,
    updatedAt: "2026-04-01T15:30:00Z",
  },
  {
    id: "conv-2",
    item: MOCK_ITEMS[2],
    participants: [MOCK_USERS[0], MOCK_USERS[2]],
    lastMessage: {
      id: "msg-5",
      conversationId: "conv-2",
      senderId: "user-1",
      content: "Perfetto, ci vediamo sabato allora!",
      isSystem: false,
      createdAt: "2026-04-01T12:00:00Z",
      isRead: true,
    },
    unreadCount: 0,
    updatedAt: "2026-04-01T12:00:00Z",
  },
  {
    id: "conv-3",
    item: MOCK_ITEMS[3],
    participants: [MOCK_USERS[0], MOCK_USERS[3]],
    lastMessage: {
      id: "msg-8",
      conversationId: "conv-3",
      senderId: "user-4",
      content: "Grazie mille! Sei gentilissimo!",
      isSystem: false,
      createdAt: "2026-03-31T18:00:00Z",
      isRead: true,
    },
    unreadCount: 0,
    updatedAt: "2026-03-31T18:00:00Z",
  },
];

export const MOCK_MESSAGES: Record<string, Message[]> = {
  "conv-1": [
    { id: "msg-0", conversationId: "conv-1", senderId: "user-1", content: "Ciao! Ho visto che hai pubblicato una giacca Zara. E ancora disponibile?", isSystem: false, createdAt: "2026-04-01T15:00:00Z", isRead: true },
    { id: "msg-1", conversationId: "conv-1", senderId: "user-2", content: "Ciao! Si, e ancora disponibile. Vuoi venire a prenderla?", isSystem: false, createdAt: "2026-04-01T15:15:00Z", isRead: true },
    { id: "msg-2", conversationId: "conv-1", senderId: "user-1", content: "Fantastico! Quando sei disponibile?", isSystem: false, createdAt: "2026-04-01T15:20:00Z", isRead: true },
    { id: "msg-3", conversationId: "conv-1", senderId: "user-2", content: "Domani pomeriggio va bene? Verso le 16?", isSystem: false, createdAt: "2026-04-01T15:30:00Z", isRead: false },
  ],
  "conv-2": [
    { id: "msg-4", conversationId: "conv-2", senderId: "user-3", content: "I libri di Harry Potter sono ancora disponibili?", isSystem: false, createdAt: "2026-04-01T10:00:00Z", isRead: true },
    { id: "msg-5", conversationId: "conv-2", senderId: "user-1", content: "Si! Vuoi passare a prenderli?", isSystem: false, createdAt: "2026-04-01T10:30:00Z", isRead: true },
    { id: "msg-6", conversationId: "conv-2", senderId: "user-3", content: "Sabato mattina posso passare, va bene?", isSystem: false, createdAt: "2026-04-01T11:00:00Z", isRead: true },
    { id: "msg-7", conversationId: "conv-2", senderId: "user-1", content: "Perfetto, ci vediamo sabato allora!", isSystem: false, createdAt: "2026-04-01T12:00:00Z", isRead: true },
  ],
};

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: "not-1", type: "item_requested", title: "Nuova richiesta!", body: "Giulia ha richiesto il tuo Monitor Samsung", data: { itemId: "item-4" }, isRead: false, createdAt: "2026-04-01T16:00:00Z" },
  { id: "not-2", type: "new_message", title: "Nuovo messaggio", body: "Giulia ti ha inviato un messaggio", data: { conversationId: "conv-1" }, isRead: false, createdAt: "2026-04-01T15:30:00Z" },
  { id: "not-3", type: "karma_milestone", title: "Traguardo raggiunto!", body: "Hai raggiunto 2000 punti karma!", data: {}, isRead: true, createdAt: "2026-03-30T10:00:00Z" },
  { id: "not-4", type: "review_received", title: "Nuova recensione", body: "Sara ti ha lasciato una recensione a 5 stelle", data: { userId: "user-4" }, isRead: true, createdAt: "2026-03-29T14:00:00Z" },
  { id: "not-5", type: "badge_earned", title: "Nuovo badge!", body: "Hai ottenuto il badge Eco Warrior!", data: {}, isRead: true, createdAt: "2026-03-28T09:00:00Z" },
  { id: "not-6", type: "nearby_item", title: "Oggetto vicino a te", body: "Nuovo oggetto disponibile a 500m da te", data: { itemId: "item-5" }, isRead: true, createdAt: "2026-03-27T11:00:00Z" },
];

export const MOCK_REVIEWS: Review[] = [
  { id: "rev-1", reviewerId: "user-4", reviewer: MOCK_USERS[3], reviewedId: "user-1", rating: 5, comment: "Gentilissimo e puntuale! Il monitor era in condizioni perfette.", createdAt: "2026-03-28T10:00:00Z" },
  { id: "rev-2", reviewerId: "user-3", reviewer: MOCK_USERS[2], reviewedId: "user-1", rating: 5, comment: "Persona affidabile, consigliato!", createdAt: "2026-03-20T14:00:00Z" },
  { id: "rev-3", reviewerId: "user-5", reviewer: MOCK_USERS[4], reviewedId: "user-1", rating: 4, comment: "Tutto bene, oggetto come descritto.", createdAt: "2026-03-15T09:00:00Z" },
  { id: "rev-4", reviewerId: "user-2", reviewer: MOCK_USERS[1], reviewedId: "user-1", rating: 5, comment: "Super disponibile e cordiale!", createdAt: "2026-03-10T16:00:00Z" },
];
